<a href="https://colab.research.google.com/github/Andrew-lee0615/value-at-risk-analysis/blob/main/01_returns.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
import yfinance as yf

In [9]:

tickers = ["NVDA","INTC", "AMD", "MU", "MRVL", "WDC", "AVGO", "SPY"]
prices = yf.download(tickers, period="5y", auto_adjust=True)["Close"]
prices.tail()

[*********************100%***********************]  8 of 8 completed

Ticker,AMD,AVGO,INTC,MRVL,MU,NVDA,SPY,WDC
Date,,,,,,,,
2026-10-09,608.099976,361.540009,104.699997,275.279999,1028.838135,229.279999,778.570007,397.279999
2026-10-12,594.239990,354.730011,101.349998,265.859985,988.884338,226.320007,778.099976,386.940002
2026-10-13,605.530029,357.309998,102.809998,268.730011,953.040039,228.520004,778.010010,380.709991
2026-10-14,570.820007,346.250000,98.120003,245.279999,914.130005,221.300003,769.599976,364.100006
2026-10-15,562.229980,344.329987,95.370003,241.240005,931.239990,217.229996,771.789978,356.450012

In [7]:
log_returns = np.log(prices / prices.shift(1)).dropna()
log_returns.head()

Ticker,AMD,AVGO,INTC,MRVL,MU,NVDA,SPY,WDC
Date,,,,,,,,
2021-10-19,-0.000859,0.013870,0.013494,0.010073,0.004598,0.003055,0.007685,0.004502
2021-10-20,0.000516,-0.001961,0.002894,-0.009775,0.010306,-0.008425,0.003920,0.013564
2021-10-21,0.024946,0.009301,0.011314,-0.001788,0.005405,0.026299,0.002605,0.006890
2021-10-22,0.004098,0.002448,-0.124187,-0.011396,-0.016600,0.001497,-0.001037,0.004392
2021-10-25,0.020977,0.012839,-0.001011,0.020302,0.018346,0.019176,0.005349,-0.003864

In [8]:
log_returns.describe()

Ticker,AMD,AVGO,INTC,MRVL,MU,NVDA,SPY,WDC
count,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000,1253.000000
mean,0.001257,0.001605,0.000513,0.001035,0.002116,0.001823,0.000489,0.001713
std,0.035920,0.027811,0.034820,0.040591,0.035703,0.032458,0.010780,0.033497
min,-0.190125,-0.191122,-0.301896,-0.220817,-0.176487,-0.185946,-0.060327,-0.201655
25%,-0.019131,-0.012761,-0.016867,-0.020578,-0.016579,-0.016518,-0.004597,-0.016252
50%,0.000210,0.000782,-0.000254,0.001127,0.001110,0.002586,0.000588,0.001722
75%,0.021158,0.015538,0.016762,0.022460,0.021047,0.020225,0.006280,0.016697
max,0.213663,0.218594,0.211879,0.281568,0.176401,0.218088,0.099863,0.155002